@startuml
left to right direction
skinparam packageStyle rectangle
actor Клиент
actor Организатор
actor Администратор

Клиент -up- (Узнать расписание)
Клиент -up- (Зарегистрироваться)
Клиент -- (Авторизация)
Клиент -- (Купить билет)
Клиент -- (Сдать билет)

(Специальные места) .> (Купить билет) : extend
(Обычные места) .-left-> (Купить билет) : extend

Организатор -- (Зарегистрироваться)
Организатор -- (Авторизация)
Организатор -- (Сформировать матч)
Организатор -- (Получить отчет)

(Сформировать матч) .> (Корректировка) : include
(По матчу) .> (Получить отчет) : extend
(По сезону) .> (Получить отчет) : extend

Администратор -- (Авторизация)
Администратор -up- (Получить отчет)
Администратор -- (Предоставить доступ)
Администратор -up- (Удалить пользователя)
@enduml

