@startuml

class Пользователь {
 +Имя
 +Фамилия
 +Отчество
 +Id
 +Авторизация()
}

class Клиент {
    +Узнать_расписание()
    +Купить_билет()
    +Сдать_билет()
}

class Матч {
    +Id
    +Описание
    +Наименование
}

class Новый_матч {
}

class Созданный_матч {
    +Статус
    +ДатаСоздания
}

class Организатор {
    +СформироватьМатч()
    +ПолучитьОтчет()
    +РедактироватьМатч()
}

class Отчет {
    +Id
    +Наименование
    +Описание
}

class Администратор {
    +ПредоставитьДоступ()
    +УдалитьПользователя()
    +ПолучитьОтчет()
}

Клиент --|> Пользователь
Организатор --|> Пользователь
Администратор --|> Пользователь

Новый_матч --|> Матч
Созданный_матч --|> Матч

Администратор <.. Отчет
Организатор <.. Отчет

Организатор <.. Матч
@enduml
