@startuml

package Пользователи {
actor Покупатель
actor Организатор
actor Администратор
}

package Система {
usecase "Узнать расписание" as UC1
usecase "Зарегистрироваться" as UC2
usecase "Авторизация" as UC3
usecase "Купить билет/абонимент" as UC4
usecase "Сдать билет/абонимент" as UC5
usecase "Сформировать матч" as UC6
usecase "Получить отчет" as UC7
usecase "Предоставить доступ" as UC8
usecase "Удалить пользователя" as UC9
}

Покупатель -- UC1
Покупатель -- UC2
Покупатель -- UC3
Покупатель -- UC4
Покупатель -- UC5

Организатор -- UC2
Организатор -- UC3
Организатор -- UC6
Организатор -- UC7

Администратор -- UC3
Администратор -- UC8
Администратор -- UC9
Администратор -- UC7
@enduml
