@startuml
participant Администратор
activate Администратор
Администратор -> Организатор :Предоставить доступ
activate Организатор
Организатор -> Матч :Создать матч
deactivate Организатор
activate Матч
Матч -> РасписаниеМатчей :Запись матча в расписание
deactivate Матч
activate РасписаниеМатчей
activate Клиент
Клиент -> РасписаниеМатчей :Узнать расписание
РасписаниеМатчей --> Клиент :Вывод календаря с матчами
activate Билет
Клиент -> Билет: Купить билет
Билет --> Клиент: Отправка билета на эл. почту
deactivate Билет
@enduml