@startuml

|Организатор|
start
:Вход в систему;
if (Аккаунт существует?) is (Да) then
:Авторизация;
else (Нет)
:Регистрация;
endif
:Вход в аккаунт;

|Администратор|
:Авторизация;
:Предоставить доступ организатору;

|Организатор|
:Создать матч;
:Внести коррективы в описание;

|Клиент|
start
:Вход в систему;
if (Аккаунт существует?) is (Да) then
:Авторизация;
else (Нет)
:Регистрация;
endif
:Вход в аккаунт;
:Узнать расписание;
:Купить билет;
stop
@enduml